<a href="https://colab.research.google.com/github/nakisa84/Springboard/blob/main/capston%202%20project/notebooks/BC_Preproccesing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Breast Cancer Survival Prediction Pre Processing**

# 1.Introduction

In the previous sections we have cleaned and explore the data. Most of the features were categorical and were converted to dummy data. Also as the data was imbalanced  SMOTE method used to add some synthetic data and eventually very nice and balanced data was produced. Also by exploring the data we have a good undrestanding of the features that can be used in our model.

In this section we conclude the data processing and make the data ready for modeling.

In [7]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.decomposition import PCA
from sklearn.preprocessing import scale
from sklearn.model_selection import train_test_split

def prepare_train_test (df,target):
    X = df.drop(target, axis = 1)
    y = df[[target]]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1)
    return X_train, X_test, y_train, y_test

# 2.Load the data

In [4]:
# loading data from colab environment
from google.colab import drive
drive.mount('/content/drive')
fpath = '/content/drive/My Drive/Springboard/capston 2 project/data/bc_data_synthetic.csv'

# loading data from Jupyter environment
# fpath = '../data/bc_data_synthetic.csv'

df = pd.read_csv(fpath)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [6]:
print(df.shape)
df.head()

(6816, 25)

   Tumor Size  Regional Node Examined  ...  Progesterone Status_Positive  Status
0          40                      19  ...                             1       0
1          45                      25  ...                             1       0
2          25                       4  ...                             1       1
3          19                      26  ...                             1       1
4          35                      21  ...                             1       1

[5 rows x 25 columns]

In [10]:
df.describe().T

                               count       mean        std  ...   50%   75%    max
Tumor Size                    6816.0  33.137617  22.410644  ...  25.0  42.0  140.0
Regional Node Examined        6816.0  14.438087   8.057787  ...  14.0  19.0   61.0
Reginol Node Positive         6816.0   5.350205   6.238651  ...   3.0   7.0   46.0
Race_Other                    6816.0   0.047829   0.213419  ...   0.0   0.0    1.0
Race_White                    6816.0   0.782277   0.412728  ...   1.0   1.0    1.0
Marital Status_Married        6816.0   0.520393   0.499621  ...   1.0   1.0    1.0
Marital Status_Separated      6816.0   0.006896   0.082759  ...   0.0   0.0    1.0
Marital Status_Single         6816.0   0.101379   0.301852  ...   0.0   0.0    1.0
Marital Status_Widowed        6816.0   0.037852   0.190852  ...   0.0   0.0    1.0
T Stage_T2                    6816.0   0.449090   0.497438  ...   0.0   1.0    1.0
T Stage_T3                    6816.0   0.140552   0.347584  ...   0.0   0.0    1.0
T Stage_T4                    6816.0   0.017019   0.129351  ...   0.0   0.0    1.0
N Stage_N2                    6816.0   0.194396   0.395764  ...   0.0   0.0    1.0
N Stage_N3                    6816.0   0.179577   0.383863  ...   0.0   0.0    1.0
6th Stage_IIB                 6816.0   0.243838   0.429428  ...   0.0   0.0    1.0
6th Stage_IIIA                6816.0   0.242077   0.428372  ...   0.0   0.0    1.0
6th Stage_IIIB                6816.0   0.010563   0.102242  ...   0.0   0.0    1.0
6th Stage_IIIC                6816.0   0.179577   0.383863  ...   0.0   0.0    1.0
Grade_Grade II                6816.0   0.458480   0.498310  ...   0.0   1.0    1.0
Grade_Grade III               6816.0   0.253521   0.435059  ...   0.0   1.0    1.0
Grade_anaplastic              6816.0   0.002788   0.052728  ...   0.0   0.0    1.0
A Stage_Regional              6816.0   0.946890   0.224270  ...   1.0   1.0    1.0
Estrogen Status_Positive      6816.0   0.829665   0.375954  ...   1.0   1.0    1.0
Progesterone Status_Positive  6816.0   0.681485   0.465935  ...   1.0   1.0    1.0
Status                        6816.0   0.500000   0.500037  ...   0.5   1.0    1.0

[25 rows x 8 columns]

There are 3 features ('Tumor Size', 'Regional Node Examined', 'Reginol Node Positive') that are continious and they do not need scaling as their scale is almost similiar. Also as calculated in the EDA notebook, the most important features are:
1.  Grade_Grade II 
2.  Progesterone Status_Positive
1.   6th Stage_IIIC
2.   Marital Status_Married
1.   Marital Status_Single
2.   Race_Other
1.   Estrogen Status_Positive


Which means we would not actually use the continious features.

# 3.Split the data to test and train

In [12]:
#split the whole data to test and train
X_train, X_test, y_train, y_test = prepare_train_test(df,'Status')

print('X train shape is:{}'.format(X_train.shape))
print('y train shape is:{}'.format(y_train.shape))
print('X test shape is:{}'.format(X_test.shape))
print('y test shape is:{}'.format(y_test.shape))

In [21]:
#save the data
X_train_fpath = '/content/drive/My Drive/Springboard/capston 2 project/data/train-test/bc_data_X_train.csv'
y_train_fpath = '/content/drive/My Drive/Springboard/capston 2 project/data/train-test/bc_data_y_train.csv'
X_test_fpath = '/content/drive/My Drive/Springboard/capston 2 project/data/train-test/bc_data_X_test.csv'
y_test_fpath = '/content/drive/My Drive/Springboard/capston 2 project/data/train-test/bc_data_y_test.csv'


X_train.to_csv(X_train_fpath, index=False)
y_train.to_csv(y_train_fpath, index=False)

X_test.to_csv(X_test_fpath, index=False)
y_test.to_csv(y_test_fpath, index=False)

In [27]:
#split selected data to test and train
df_feature_selection = df[['Grade_Grade II','Progesterone Status_Positive','6th Stage_IIIC','Marital Status_Married','Estrogen Status_Positive','Status']]
X_train, X_test, y_train, y_test = prepare_train_test(df_feature_selection,'Status')

print('X train shape is:{}'.format(X_train.shape))
print('y train shape is:{}'.format(y_train.shape))
print('X test shape is:{}'.format(X_test.shape))
print('y test shape is:{}'.format(y_test.shape))

X train shape is:(4566, 5)
y train shape is:(4566, 1)
X test shape is:(2250, 5)
y test shape is:(2250, 1)

In [28]:
#save the data
X_train_fpath = '/content/drive/My Drive/Springboard/capston 2 project/data/train-test/bc_data_X_train_selected.csv'
y_train_fpath = '/content/drive/My Drive/Springboard/capston 2 project/data/train-test/bc_data_y_train_selected.csv'
X_test_fpath = '/content/drive/My Drive/Springboard/capston 2 project/data/train-test/bc_data_X_test_selected.csv'
y_test_fpath = '/content/drive/My Drive/Springboard/capston 2 project/data/train-test/bc_data_y_test_selected.csv'


X_train.to_csv(X_train_fpath, index=False)
y_train.to_csv(y_train_fpath, index=False)

X_test.to_csv(X_test_fpath, index=False)
y_test.to_csv(y_test_fpath, index=False)